Micronaut Kotlin example
mirage22/fw-monitoring-examples pull request #8
Opened 2022-03-03 16:54 UTC by chrisime

2022-03-04 11:42 UTC, mirage22 requested changes

2022-03-04 11:42 UTC, mirage22 commented on micronaut-monitoring/src/main/java/com/wengnerits/monitoring/micronaut/controller/MainController.java
> -@Controller("/")
is possible to revert this changes in "micronaut-monitoring" module as it's not a part for the "micronaut-kotlin-monitoring" ?

2022-03-04 11:42 UTC, mirage22 commented on settings.gradle
> +include 'micronaut-monitoring-kt'
is possible to follow proposed naming <framework>-<language>-<purpose>, example _micronaut-kt-monitoring_ ?

2022-03-04 17:30 UTC, chrisime commented
@mirage22 all resolved, ready to be merged

2022-03-11 12:43 UTC, mirage22 approved these changes

2022-03-11 12:44 UTC, merged